bag/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("", views.view_bag, name="view_bag"),
    path("add/<item_id>/", views.add_to_bag, name="add_to_bag"),
    path("adjust/<item_id>/", views.adjust_bag, name="adjust_bag"),
    path("remove/<item_id>/", views.remove_from_bag, name="remove_from_bag"),
]

faq/urls.py
from . import views
from django.urls import path

urlpatterns = [
    path("", views.faq, name="faq"),
]

vintage/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("allauth.urls")),
    path("", include("home.urls")),
    path("products/", include("products.urls")),
    path("bag/", include("bag.urls")),
    path("checkout/", include("checkout.urls")),
    path("profile/", include("profiles.urls")),
    path("contact/", include("contact.urls")),
    path("faq/", include("faq.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


handler400 = "vintage.views.error_400"
handler403 = "vintage.views.error_403"
handler404 = "vintage.views.error_404"
handler500 = "vintage.views.error_500"

faq/models.py
from django.db import models


class Question(models.Model):
    question_text = models.TextField()

    def __str__(self):
        return self.question_text


class Answer(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    answer_text = models.TextField()

    def __str__(self):
        return self.answer_text

faq/views.py
from django.shortcuts import render

from .models import Question


def faq(request):
    questions = Question.objects.all()
    return render(request, "faq/faq.html", {"questions": questions})

faq/templates/faq/faq.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col faq">
                <h2 class="text-center mt-5">FAQs</h2>
                <p class="mt-5 mb-5">
                    Welcome to our Frequently Asked Questions (FAQs) page. Here, you'll find answers 
                    to common queries about our vintage products, purchasing process, and policies. 
                    We aim to provide all the information you need to make your shopping experience 
                    seamless and enjoyable. If you have any additional questions, please don't hesitate 
                    to contact our customer service team.
                </p>
            </div>
        </div>
    </div>


    <div class="container">
        <div class="row card faq-card">
            <div class="col card-body">
                <ul>
                {% for question in questions %}
                <li><strong>{{ question.question_text }}</strong></li>
                {% for answer in question.answer_set.all %}
                <li class="answers ml-3 mb-3">{{ answer.answer_text }}</li>
                {% endfor %}
                {% endfor %}
                </ul>
            </div>
        </div>
    </div>    
{% endblock %}