bag/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("", views.view_bag, name="view_bag"),
    path("add/<item_id>/", views.add_to_bag, name="add_to_bag"),
    path("adjust/<item_id>/", views.adjust_bag, name="adjust_bag"),
    path("remove/<item_id>/", views.remove_from_bag, name="remove_from_bag"),
]

products/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("", views.all_products, name="products"),
    path("<int:product_id>/", views.product_detail, name="product_detail"),
    path("add/", views.add_product, name="add_product"),
    path("edit/<int:product_id>/", views.edit_product, name="edit_product"),
    path(
        "delete/<int:product_id>/", views.delete_product, name="delete_product"
    ),
    path("wishlist/", views.wishlist, name="wishlist"),
    path(
        "addwishlist/<int:product_id>/",
        views.add_to_wishlist,
        name="add_to_wishlist",
    ),
    path(
        "removewishlist/<int:product_id>/",
        views.remove_from_wishlist,
        name="remove_from_wishlist",
    ),
    path(
        "<int:product_id>/edit_review/<int:review_id>",
        views.edit_review,
        name="edit_review",
    ),
    path(
        "<int:product_id>/delete_review/<int:review_id>",
        views.delete_review,
        name="delete_review",
    ),
]

vintage/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("allauth.urls")),
    path("", include("home.urls")),
    path("products/", include("products.urls")),
    path("bag/", include("bag.urls")),
    path("checkout/", include("checkout.urls")),
    path("profile/", include("profiles.urls")),
    path("contact/", include("contact.urls")),
    path("faq/", include("faq.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


handler400 = "vintage.views.error_400"
handler403 = "vintage.views.error_403"
handler404 = "vintage.views.error_404"
handler500 = "vintage.views.error_500"

checkout/models.py
import uuid

from django.db import models
from django.db.models import Sum
from django.conf import settings

from django_countries.fields import CountryField

from products.models import Product
from profiles.models import UserProfile


class Order(models.Model):
    order_number = models.CharField(max_length=32, null=False, editable=False)
    user_profile = models.ForeignKey(
        UserProfile,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name="orders",
    )
    full_name = models.CharField(max_length=50, null=False, blank=False)
    email = models.EmailField(max_length=254, null=False, blank=False)
    phone_number = models.CharField(max_length=20, null=False, blank=False)
    country = CountryField(blank_label="Country *", null=False, blank=False)
    postcode = models.CharField(max_length=20, null=True, blank=True)
    town_or_city = models.CharField(max_length=40, null=False, blank=False)
    street_address1 = models.CharField(max_length=80, null=False, blank=False)
    street_address2 = models.CharField(max_length=80, null=True, blank=True)
    county = models.CharField(max_length=80, null=True, blank=True)
    date = models.DateTimeField(auto_now_add=True)
    delivery_cost = models.DecimalField(
        max_digits=6, decimal_places=2, null=False, default=0
    )
    order_total = models.DecimalField(
        max_digits=10, decimal_places=2, null=False, default=0
    )
    grand_total = models.DecimalField(
        max_digits=10, decimal_places=2, null=False, default=0
    )
    original_bag = models.TextField(null=False, blank=False, default="")
    stripe_pid = models.CharField(
        max_length=254, null=False, blank=False, default=""
    )

    def _generate_order_number(self):
        """
        Generate a random, unique order number using UUID
        """
        return uuid.uuid4().hex.upper()

    def update_total(self):
        """
        Update grand total each time a line item is added,
        accounting for delivery costs.
        """
        self.order_total = (
            self.lineitems.aggregate(Sum("lineitem_total"))[
                "lineitem_total__sum"
            ]
            or 0
        )
        if self.order_total < settings.FREE_DELIVERY_THRESHOLD:
            self.delivery_cost = (
                self.order_total * settings.STANDARD_DELIVERY_PERCENTAGE / 100
            )
        else:
            self.delivery_cost = 0
        self.grand_total = self.order_total + self.delivery_cost
        self.save()

    def save(self, *args, **kwargs):
        """
        Override the original save method to set the order number
        if it hasn't been set already.
        """
        if not self.order_number:
            self.order_number = self._generate_order_number()
        super().save(*args, **kwargs)

    def __str__(self):
        return self.order_number


class OrderLineItem(models.Model):
    order = models.ForeignKey(
        Order,
        null=False,
        blank=False,
        on_delete=models.CASCADE,
        related_name="lineitems",
    )
    product = models.ForeignKey(
        Product, null=False, blank=False, on_delete=models.CASCADE
    )
    product_size = models.CharField(
        max_length=2, null=True, blank=True
    )  # XS, S, M, L, XL
    quantity = models.IntegerField(null=False, blank=False, default=0)
    lineitem_total = models.DecimalField(
        max_digits=6, decimal_places=2, null=False, blank=False, editable=False
    )

    def save(self, *args, **kwargs):
        """
        Override the original save method to set the lineitem total
        and update the order total.
        """
        self.lineitem_total = self.product.price * self.quantity
        super().save(*args, **kwargs)

    def __str__(self):
        return f"SKU {self.product.sku} on order {self.order.order_number}"

products/forms.py
from django import forms

from .models import Category, Product, Review
from .widgets import CustomClearableFileInput


class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = "__all__"

    image = forms.ImageField(
        label="Image", required=False, widget=CustomClearableFileInput
    )

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        categories = Category.objects.all()
        friendly_names = [(c.id, c.get_friendly_name()) for c in categories]

        self.fields["category"].choices = friendly_names
        for field_name, field in self.fields.items():
            field.widget.attrs["class"] = "border-black rounded-0"


class ReviewForm(forms.ModelForm):
    """
    Review form for user to edit review
    """

    class Meta:
        model = Review
        fields = ("content",)
        labels = {"content": "Your review:"}


class AddToWishlistForm(forms.Form):
    pass

products/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.db.models import Q
from django.db.models.functions import Lower
from django.shortcuts import get_object_or_404, redirect, render, reverse

from .forms import AddToWishlistForm, ProductForm, ReviewForm
from .models import Category, Product, Review, Wishlist

# Create your views here.


def all_products(request):
    """A view to show all products, including sorting and search queries"""

    products = Product.objects.all()
    query = None
    categories = None
    sort = None
    direction = None

    if request.GET:
        if "sort" in request.GET:
            sortkey = request.GET["sort"]
            sort = sortkey
            if sortkey == "name":
                sortkey = "lower_name"
                products = products.annotate(lower_name=Lower("name"))
            if sortkey == "category":
                sortkey = "category__name"
            if "direction" in request.GET:
                direction = request.GET["direction"]
                if direction == "desc":
                    sortkey = f"-{sortkey}"
            products = products.order_by(sortkey)

        if "category" in request.GET:
            categories = request.GET["category"].split(",")
            products = products.filter(category__name__in=categories)
            categories = Category.objects.filter(name__in=categories)

        if "q" in request.GET:
            query = request.GET["q"]
            if not query:
                messages.error(
                    request, "You didn't enter any search criteria!"
                )
                return redirect(reverse("products"))

            queries = Q(name__icontains=query) | Q(
                description__icontains=query
            )
            products = products.filter(queries)

    current_sorting = f"{sort}_{direction}"

    context = {
        "products": products,
        "search_term": query,
        "current_categories": categories,
        "current_sorting": current_sorting,
    }

    return render(request, "products/products.html", context)


def product_detail(request, product_id):
    """A view to show individual product details"""

    product = get_object_or_404(Product, pk=product_id)

    # Display only approved reviews
    reviews = product.reviews.order_by("-created_on")

    # Display a form to users, so they can add review
    skip_shopping_bag = False

    req_context = request.session.get("context", None)
    if req_context:
        del request.session["context"]
        skip_shopping_bag = req_context["skip_shopping_bag"]

    if request.user.is_authenticated:
        review_form = ReviewForm(data=request.POST)

        if review_form.is_valid():
            review = review_form.save(commit=False)
            review.author = request.user
            review.product = product
            review.save()
            messages.success(
                request,
                "Thank you for taking \
                the time to leave a review of this product",
            )
            skip_shopping_bag = True

    context = {
        "product": product,
        "reviews": reviews,
        "review_form": ReviewForm(),
        "skip_shopping_bag": skip_shopping_bag,
    }

    return render(request, "products/product_detail.html", context)


@login_required
def add_product(request):
    """Add a product to the store"""
    if not request.user.is_superuser:
        messages.error(request, "Sorry, only store owners can do that.")
        return redirect(reverse("home"))

    if request.method == "POST":
        form = ProductForm(request.POST, request.FILES)
        if form.is_valid():
            product = form.save()
            messages.success(request, "Successfully added product!")
            return redirect(reverse("product_detail", args=[product.id]))
        else:
            messages.error(
                request,
                "Failed to add product. Please ensure the form is valid.",
            )
    else:
        form = ProductForm()

    template = "products/add_product.html"
    context = {
        "form": form,
    }

    return render(request, template, context)


@login_required
def edit_product(request, product_id):
    """Edit a product in the store"""
    if not request.user.is_superuser:
        messages.error(request, "Sorry, only store owners can do that.")
        return redirect(reverse("home"))

    product = get_object_or_404(Product, pk=product_id)
    if request.method == "POST":
        form = ProductForm(request.POST, request.FILES, instance=product)
        if form.is_valid():
            form.save()
            messages.success(request, "Successfully updated product!")
            return redirect(reverse("product_detail", args=[product.id]))
        else:
            messages.error(
                request,
                "Failed to update product. Please ensure the form is valid.",
            )
    else:
        form = ProductForm(instance=product)
        messages.info(request, f"You are editing {product.name}")

    template = "products/edit_product.html"

    context = {
        "form": form,
        "product": product,
    }

    return render(request, template, context)


@login_required
def delete_product(request, product_id):
    """Delete a product from the store"""
    if not request.user.is_superuser:
        messages.error(request, "Sorry, only store owners can do that.")
        return redirect(reverse("home"))

    product = get_object_or_404(Product, pk=product_id)
    product.delete()
    messages.success(request, "Product deleted!")
    return redirect(request.build_absolute_uri())


@login_required
def edit_review(request, product_id, review_id):
    """
    View to edit reviews
    """
    # Display only approved reviews
    product = get_object_or_404(Product, pk=product_id)

    if request.method == "POST":
        review = get_object_or_404(Review, pk=review_id)
        review_form = ReviewForm(data=request.POST, instance=review)

        # If the form is invalid or someone other than the author tries to edit
        # the review then that's not allowed an a error message is shown
        if review_form.is_valid() and review.author == request.user:
            review = review_form.save(commit=False)
            review.product = product
            review.approved = False
            review.save()
            messages.add_message(request, messages.SUCCESS, "Review Updated!")
        else:
            messages.add_message(
                request, messages.ERROR, "Error updating review!"
            )

    return redirect(reverse("product_detail", args=[product_id]))


@login_required
def delete_review(request, product_id, review_id):
    """
    view to delete reviews
    """
    review = get_object_or_404(Review, pk=review_id)

    if review.author == request.user:
        review.delete()
        messages.add_message(request, messages.SUCCESS, "Review deleted!")
    else:
        messages.add_message(
            request, messages.ERROR, "You can only delete your own reviews!"
        )

    context = {"skip_shopping_bag": True}
    request.session["context"] = context
    return redirect(reverse("product_detail", args=[product_id]))


@login_required
def wishlist(request):
    try:
        # Attempt to get the existing Wishlist instance for the user
        wishlist = Wishlist.objects.get(user=request.user)
    except Wishlist.DoesNotExist:
        # If no Wishlist exists, create one
        wishlist = Wishlist.objects.create(user=request.user)

    wishlist_items = wishlist.items.all()

    # Get the context in case it comes from remove_from_wishlist
    req_context = request.session.get("context", None)
    skip_shopping_bag = False
    # Delete the context from the request in case it keeps getting redirected
    if req_context:
        del request.session["context"]
        skip_shopping_bag = req_context["skip_shopping_bag"]
    context = {
        "products": wishlist_items,
        "is_wishlist": True,
        "skip_shopping_bag": skip_shopping_bag,
    }
    return render(
        request,
        "products/wish_list.html",
        context,
    )


@login_required
def add_to_wishlist(request, product_id):
    product = Product.objects.get(pk=product_id)
    reviews = product.reviews.order_by("-created_on")
    if request.method == "POST":
        form = AddToWishlistForm(request.POST)
        if form.is_valid():
            if Wishlist.objects.filter(
                user=request.user, items__pk=product.pk
            ).exists():
                messages.warning(
                    request,
                    f"{product.name} is already added to your Wishlist.",
                )
            else:
                wishlist = Wishlist.objects.get(user=request.user)
                wishlist.items.add(product)
                messages.success(
                    request, f"Added {product.name} to your Wishlist"
                )
    else:
        form = AddToWishlistForm()  # Initialize the form for GET requests

    context = {
        "form": form,
        "product": product,
        "reviews": reviews,
        "review_form": ReviewForm(),
        "skip_shopping_bag": True,
    }
    return render(
        request,
        "products/product_detail.html",
        context,
    )


@login_required
def remove_from_wishlist(request, product_id):
    product = get_object_or_404(Product, pk=product_id)
    wishlist = request.user.wishlist
    wishlist.items.remove(product)
    messages.success(request, "Product deleted from Wishlist!")
    # Because I want to show the message but not the shopping bag
    # I'm using Django session framework to skip it in the templates
    # ("base.html")
    context = {"skip_shopping_bag": True}
    request.session["context"] = context
    return redirect(reverse("wishlist"))

products/templates/products/add_product.html
{% extends "base.html" %}
{% load static %}

{% block page_header %}
    <div class="container header-container">
        <div class="row">
            <div class="col"></div>
        </div>
    </div>
{% endblock %}

{% block content %}
    <div class="overlay"></div>
    <div class="container">
        <div class="row">
            <div class="col-12 col-md-6">
                <hr>
                <h2 class="logo-font mb-4">Product Management</h2>
                <h5 class="text-muted">Add a Product</h5>
                <hr>
            </div>
        </div>

        <div class="row">
            <div class="col-12 col-md-6">
                <form method="POST" action="{% url 'add_product' %}" class="form mb-2" enctype="multipart/form-data">
                    {% csrf_token %}
                    {% for field in form %}
                        {% if field.name != 'image' %}
                            {{ field | as_crispy_field }}
                        {% else %}
                            {{ field }}
                        {% endif %}
                    {% endfor %}
                    <div class="text-right">
                        <a class="btn btn-outline-black rounded-0" href="{% url 'products' %}">Cancel</a>
                        <button class="btn btn-black rounded-0" type="submit" aria-label="AddProduct">Add Product</button>
                    </div>
                </form>
            </div>            
        </div>
    </div>
{% endblock %}

{% block postloadjs %}
    {{ block.super }}
    <script>
        $('#new-image').change(function() {
            var file = $('#new-image')[0].files[0];
            $('#filename').text(`Image will be set to: ${file.name}`);
        });
    </script>
{% endblock %}

products/templates/products/edit_product.html
{% extends "base.html" %}
{% load static %}

{% block page_header %}
    <div class="container header-container">
        <div class="row">
            <div class="col"></div>
        </div>
    </div>
{% endblock %}

{% block content %}
    <div class="overlay"></div>
    <div class="container">
        <div class="row">
            <div class="col-12 col-md-6">
                <hr>
                <h2 class="logo-font mb-4">Product Management</h2>
                <h5 class="text-muted">Edit a Product</h5>
                <hr>
            </div>
        </div>

        <div class="row">
            <div class="col-12 col-md-6">
                <form method="POST" action="{% url 'edit_product' product.id %}" class="form mb-2" enctype="multipart/form-data">
                    {% csrf_token %}
                    {% for field in form %}
                        {% if field.name != 'image' %}
                            {{ field | as_crispy_field }}
                        {% else %}
                            {{ field }}
                        {% endif %}
                    {% endfor %}
                    <div class="text-right">
                        <a class="btn btn-outline-black rounded-0" href="{% url 'products' %}">Cancel</a>
                        <button class="btn btn-black rounded-0" type="submit" aria-label="UpdateProduct">Update Product</button>
                    </div>
                </form>
            </div>            
        </div>
    </div>
{% endblock %}

{% block postloadjs %}
    {{ block.super }}
    <script>
        $('#new-image').change(function() {
            var file = $('#new-image')[0].files[0];
            $('#filename').text(`Image will be set to: ${file.name}`);
        });
    </script>
{% endblock %}

products/templates/products/product_detail.html
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_tags %}

{% block page_header %}
    <div class="container header-container">
        <div class="row">
            <div class="col"></div>
        </div>
    </div>
{% endblock %}

{% block content %}
    <div class="container-fluid">
            <div class="row justify-content-center">
                <div class="flex-fill col-12 col-md-6 col-lg-3 mb-5 mt-md-5">
                    {% if product.image %}
                    <a href="{{ product.image.url }}" target="_blank">
                        <img class="card-img-top img-fluid" src="{{ product.image.url }}" alt="{{ product.name }}">
                    </a>
                    {% else %}
                    <a href="">
                        <img class="card-img-top img-fluid" src="{{ MEDIA_URL }}noimage.png" alt="{{ product.name }}">
                    </a>
                    {% endif %}
                </div>
                <div class="flex-fill col-12 col-md-6 col-lg-3 mb-5 mt-md-5">
                    <p class="mb-0">{{ product.name }}</p>
                    <p class="lead mb-0 text-left font-weight-bold">${{ product.price }}</p>
                    {% if product.category %}
                    <p class="small mt-1 mb-0">
                        <a class="text-muted" href="{% url 'products' %}?category={{ product.category.name }}">
                            <i class="fas fa-tag mr-1"></i>{{ product.category.friendly_name }}
                        </a>
                    </p>
                    {% endif %}
                    {% if product.rating %}
                        <small class="text-muted"><i class="fas fa-star mr-1"></i>{{ product.rating }} / 5</small>
                    {% else %}
                        <small class="text-muted">No Rating</small>
                    {% endif %}
                    {% if request.user.is_superuser %}
                        <small class="ml-3">
                            <a href="{% url 'edit_product' product.id %}">Edit</a> | 
                            <a class="text-danger" href="{% url 'delete_product' product.id %}">Delete</a>
                        </small>
                    {% endif %}
                    <p class="mt-3">{{ product.description }}</p>
                    <form class="form" action="{% url 'add_to_bag' product.id %}" method="POST">
                        {% csrf_token %}
                        <div class="form-row">
                            {% with product.has_sizes as s %}
                            {% if s %}
                                <div class="col-12">
                                    <p><strong>Size:</strong></p>
                                    <select class="form-control rounded-0 w-50" name="product_size" id='id_product_size'>
                                        <option value="xs">XS</option>
                                        <option value="s">S</option>
                                        <option value="m" selected>M</option>
                                        <option value="l">L</option>
                                        <option value="xl">XL</option>
                                    </select>
                                </div>
                            {% endif %}
                            <div class="col-12">
                                <p class="mt-3"><strong>Quantity:</strong></p>
                                <div class="form-group w-50">
                                    <div class="input-group">
                                        <div class="input-group-prepend">
                                            <button class="decrement-qty btn btn-black rounded-0" aria-label="DecrementQty"
                                                data-item_id="{{ product.id }}" id="decrement-qty_{{ product.id }}">
                                                <span class="icon">
                                                    <i class="fas fa-minus"></i>
                                                </span>
                                            </button>
                                        </div>
                                        <label for="id_qty_{{ product.id }}" class="sr-only">Quantity</label>
                                        <input class="form-control qty_input" type="number"
                                            name="quantity" value="1" min="1" max="99"
                                            data-item_id="{{ product.id }}"
                                            id="id_qty_{{ product.id }}">
                                        <div class="input-group-append">
                                            <button class="increment-qty btn btn-black rounded-0" aria-label="IncrementQty"
                                                data-item_id="{{ product.id }}" id="increment-qty_{{ product.id }}">
                                                <span class="icon">
                                                    <i class="fas fa-plus"></i>
                                                </span>
                                            </button>
                                        </div>
                                    </div>
                                </div>
                            </div>

                            <div class="col{% if s %}-12 mt-2{% endif %}">
                                <a href="{% url 'products' %}" class="btn btn-outline-black rounded-0 mt-5">
                                    <span class="icon">
                                        <i class="fa-solid fa-chevron-left keep_shopping"></i>
                                    </span>
                                    <span class="text-uppercase">Keep Shopping</span>
                                </a>
                                <label for="add_to_bag" class="sr-only">Add to Bag</label>
                                <input type="submit" class="btn btn-black rounded-0 text-uppercase mt-5" value="Add to Bag" id="add_to_bag">
                            </div>
                            <label for="some_last_input" class="sr-only">Ha</label>
                            <input type="hidden" name="redirect_url" value="{{ request.path }}" id="some_last_input">
                            {% endwith %}
                        </div>
                    </form>
                    <form method="post" action="{% url 'add_to_wishlist' product.id %}">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="btn btn-warning rounded-0 text-uppercase mt-5" aria-label="AddToWishlist">Add to Wishlist</button>
                    </form>
                </div>
            </div>
    </div>
    <!--- Product Reviews -->
    <div class="container-fluid reviews" id="scroll-here">
        <div class="row justify-content-center">
            <div class="col col-lg-6">
                <!-- Creating new reviews -->
                {% if user.is_authenticated %}
                <div class="card mb-4 mt-3 card-width card-border">
                    <div class="card-body">
                        <form id="reviewForm" method="POST">
                            <h3>Leave a review</h3>
                            <p>Posting as: {{ user.username }}</p>
                            {{ review_form | crispy }}
                            {% csrf_token %}
                            <button id="submitButton" type="submit" class="btn btn-success" aria-label="Submit">Submit</button>
                        </form>
                    </div>
                </div>
                {% else %}
                <div class="mb-5">
                    <h4 class="leave-review">Would you like to leave a review for this product?</h4>
                    <p class="login-first">Please <a href="{% url 'account_login' %}">login or register</a> first</p>
                </div>
                {% endif %}
                <!-- Displaying Reviews -->
                <div class="mb-4  mt-3 reviews-display">
                    <div class="reviews-title mt-3 ml-3">
                        <h3>Product Reviews:</h3>
                    </div>
                    <div class="ml-3 mt-3 mb-2">
                        {% for review in reviews %}
                        <div class="p-2
                                {% if not review.approved and review.author == user %}
                                faded{% elif not review.approved %} d-none{% else %} approved-review{% endif %}">
                            <p class="font-weight-bold">
                            {{ review.author }}
                            <span class="font-weight-normal">
                                {{ review.created_on }}
                            </span> wrote:
                            </p>
                            <div id="review{{ review.id }}">
                            {{ review.content | linebreaks }}
                            </div>
                            {% if not review.approved and review.author == user %}
                            <p class="approval">
                            This review is awaiting approval
                            </p>
                            {% endif %}
                            {% if user.is_authenticated and review.author == user %}
                            <button class="btn btn-review-edit mr-3" aria-label="Edit" review_id="{{ review.id }}">Edit</button>
                            <button class="btn btn-review-delete" aria-label="Delete" review_id="{{ review.id }}">Delete</button>
                            {% endif %}
                            <hr>
                        </div>
                        {% empty %}
                            <p>No reviews yet, be the first to leave a review.</p>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
    </div>

<!-- Delete confirmation modal -->
<div class="modal fade" id="deleteModal" tabindex="-1" aria-labelledby="deleteModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content box-modal">
            <div class="modal-header">
                <h5 class="modal-title" id="deleteModalLabel">Delete review?</h5>
                <button id="close-review-modal" type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                Are you sure you want to delete your review? This action cannot be undone.
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal" aria-label="Close">Close</button>
                <a id="deleteConfirm" href="#" class="btn btn-danger">Delete</a>
            </div>
        </div>
    </div>
</div>
{% endblock %}

{% block postloadjs %}
    <script src="{% static 'js/reviews.js' %}"></script>
{{ block.super }}
{% include 'products/includes/quantity_input_script.html' %}
{% endblock %}